### ISSUE TITLE
renaming of buildserver to builds break docker images

### ISSUE THREAD

**Issue by vincentserpoul** [caddyserver/builds#1]
Hi,

I am the author of https://github.com/vincentserpoul/docaddy, an docker image built automatically when there is a release of caddy.
The latest v0.10.8 is still using the "github.com/caddyserver/buildworker" in its https://github.com/mholt/caddy/blob/v0.10.8/caddy/build.go but the repo has been renamed so it doesn't exist anymore.
I don't think I'm the only one relying on this, https://github.com/jumanjihouse/docker-caddy from which I mostly inspired my build repo is using it as well.

It would be great to release a new version that will take into account the build renaming

**Comment by mholt** [comment]
Oops, sorry about that. The build.go program is so new (literally just released with 0.10.8) that I didn't think anyone was relying on it. This community always surprises me :smile: 

I will be releasing a new version later today or tomorrow!

**Comment by vincentserpoul** [comment]
thanks! Continue the great work
